### ISSUE TITLE
Tối ưu hóa UX trên homepage/platform nói chung

### ISSUE THREAD

**Issue by constfang** [trungngv/khocw#17]
![image](https://cloud.githubusercontent.com/assets/17168922/13173838/194fecb4-d700-11e5-9778-1b83fad7d8bf.png)

Lỗi Font

![image](https://cloud.githubusercontent.com/assets/17168922/13174102/c878c160-d701-11e5-8592-7b3a6c714062.png)

![image](https://cloud.githubusercontent.com/assets/17168922/13174125/e8df72d2-d701-11e5-9845-134a04ad202c.png)

Add thêm "Trang chủ" vào dãy link hàng dưới (hiện giờ ko có link nào để thông từ study.kienhoc.vn ra kienhoc.vn

**Comment by alexthered** [comment]
i am on it
